version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - ncalteen
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    assignees:
      - ncalteen
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      development:
        dependency-type: development
        update-types:
          - minor
          - patch
      production:
        dependency-type: production
        update-types:
          - patch
