#############################
## JavaScript Linter rules ##
#############################

env:
  node: true
  es6: true
  jest: true
  commonjs: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2020
  sourceType: module

plugins:
  - jest
  - '@typescript-eslint'

rules:
  prettier/prettier: error
  i18n-text/no-en: off
  no-useless-escape: off
  no-case-declarations: off

extends:
  - eslint:recommended
  - plugin:github/recommended
  - plugin:jest/recommended
